import { Activity, CheckCircle2, RefreshCcw, Server, ShieldCheck, Wifi } from 'lucide-react';
import { useState } from 'react';
import type { Role } from '../data';

type HealthData = { status: string; latencyMs: number; checkedAt: string; services: Array<{ name: string; status: string }> };
export function HealthView({ role: _role, data, onRefresh, onAction }: { role: Role; data: HealthData | null; onRefresh: () => Promise<void>; onAction: (message: string) => void }) {
  const [busy, setBusy] = useState(false);
  async function refresh() { setBusy(true); try { await onRefresh(); onAction('Platform health refreshed.'); } catch (error) { onAction(error instanceof Error ? error.message : 'Health check failed.'); } finally { setBusy(false); } }
  const serviceIcons = [ShieldCheck, Server, Wifi, Activity];
  return <section className="health-page page-enter"><div className="section-heading"><div><span className="eyebrow">Global platform</span><h2>Platform health</h2><p>Live reachability checks for the shared Supabase-backed admin service.</p></div><button className="button button-secondary" onClick={refresh} disabled={busy}><RefreshCcw size={14} />{busy ? 'Checking...' : 'Refresh'}</button></div><div className="health-grid"><article className="panel health-summary"><span className="health-mark"><CheckCircle2 size={25} /></span><span className="eyebrow">Current status</span><h2>{data?.status === 'operational' ? 'All core systems operational' : 'Health check pending'}</h2><p>{data ? `Database responded in ${data.latencyMs}ms at ${new Date(data.checkedAt).toLocaleTimeString('en-IN')}.` : 'Run a health check to measure service reachability.'}</p><div className="health-score"><strong>{data?.status === 'operational' ? '99.98%' : '--'}</strong><span>service availability target</span></div><div className="health-bars">{Array.from({ length: 30 }, (_, index) => <i key={index} className={index === 18 && data?.status !== 'operational' ? 'warning' : ''} />)}</div><small>Detailed provider uptime remains owned by the infrastructure platform.</small></article><div className="service-list">{(data?.services || [{ name: 'Authentication', status: 'pending' }, { name: 'Database API', status: 'pending' }, { name: 'Realtime', status: 'pending' }, { name: 'Background jobs', status: 'pending' }]).map(({ name, status }, index) => { const Icon = serviceIcons[index] || Server; return <article className="panel service-row" key={name}><span className="service-icon"><Icon size={18} /></span><div><strong>{name}</strong><span><i />{status}</span></div><dl><div><dt>Status</dt><dd>{status}</dd></div><div><dt>Latency</dt><dd>{data ? `${data.latencyMs}ms` : '--'}</dd></div></dl></article>; })}</div></div></section>;
}
