import { BellRing, CheckCheck, ChevronRight, Filter } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import type { NotificationRecord } from '../lib/api';

const PAGE_SIZE = 6;
export function NotificationCenter({ items, onRead, onReadAll, onAction }: { items: NotificationRecord[]; onRead: (id: string) => Promise<void>; onReadAll: () => Promise<void>; onAction: (message: string) => void }) {
  const [filter, setFilter] = useState<'all' | 'unread'>('all');
  const [page, setPage] = useState(1);
  const filtered = useMemo(() => filter === 'unread' ? items.filter((item) => item.unread) : items, [filter, items]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const safePage = Math.min(page, pageCount);
  const visible = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE);
  useEffect(() => setPage(1), [filter]);
  return <section className="notification-page page-enter"><div className="notification-summary"><div><strong>{items.filter((item) => item.unread).length}</strong><span>unread operational updates</span></div><button className="button button-secondary" onClick={() => onReadAll().then(() => onAction('All notifications marked as read.'))}><CheckCheck size={14} />Mark all read</button></div><div className="panel notification-center-panel"><div className="notification-toolbar"><div className="notification-tabs" role="tablist" aria-label="Notification filters"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')} role="tab" aria-selected={filter === 'all'}>All <span>{items.length}</span></button><button className={filter === 'unread' ? 'active' : ''} onClick={() => setFilter('unread')} role="tab" aria-selected={filter === 'unread'}>Unread <span>{items.filter((item) => item.unread).length}</span></button></div><button className="button button-secondary" onClick={() => onAction('Use the unread filter to focus on pending operations.')}><Filter size={14} />Categories</button></div><div className="notification-center-list">{visible.map((item) => <button key={item.id} className={item.unread ? 'unread' : ''} onClick={() => onRead(item.id).then(() => onAction(`${item.title} opened.`))}><span className="notification-center-icon"><BellRing size={17} /></span><span className="notification-center-copy"><span><b>{item.type}</b>{item.unread && <i>New</i>}</span><strong>{item.title}</strong><small>{item.detail}</small></span><time>{new Date(item.created_at).toLocaleString('en-IN')}</time><ChevronRight size={16} className="notification-chevron" /></button>)}{visible.length === 0 && <div className="notification-empty"><BellRing size={22} /><strong>You are caught up</strong><span>No unread operational updates remain.</span></div>}</div>{filtered.length > 0 && <div className="notification-pagination"><span>Page {safePage} of {pageCount}</span><nav className="pagination" aria-label="Notification pagination"><button disabled={safePage === 1} onClick={() => setPage((current) => Math.max(1, current - 1))}>Previous</button><button disabled={safePage === pageCount} onClick={() => setPage((current) => Math.min(pageCount, current + 1))}>Next</button></nav></div>}</div></section>;
}
