import { Save, ShieldCheck } from 'lucide-react';
import { useEffect, useState } from 'react';

export type WorkspaceSettings = { display_name: string; support_email: string; admin_notice: string; digest_enabled: boolean; moderation_alerts: boolean };

export function SettingsView({ scope, settings, onSave, onAction }: { scope: string; settings: WorkspaceSettings | null; onSave: (next: WorkspaceSettings) => Promise<void>; onAction: (message: string) => void }) {
  const [form, setForm] = useState<WorkspaceSettings>({ display_name: scope, support_email: '', admin_notice: '', digest_enabled: true, moderation_alerts: true });
  const [busy, setBusy] = useState(false);
  useEffect(() => { if (settings) setForm(settings); }, [settings]);
  function set<K extends keyof WorkspaceSettings>(key: K, value: WorkspaceSettings[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit() { setBusy(true); try { await onSave(form); onAction('Workspace settings saved.'); } catch (error) { onAction(error instanceof Error ? error.message : 'Could not save settings.'); } finally { setBusy(false); } }
  return <section className="settings-page page-enter"><div className="section-heading"><div><span className="eyebrow">{scope}</span><h2>Workspace settings</h2><p>Changes apply to the assigned workspace and are recorded for audit.</p></div><button className="button button-primary" onClick={submit} disabled={busy}><Save size={14} />{busy ? 'Saving...' : 'Save changes'}</button></div><div className="settings-layout"><article className="panel settings-form"><div className="form-section"><div><h3>Campus identity</h3><p>Displayed in campus-owned operational content.</p></div><div className="form-fields"><label><span>Display name</span><input value={form.display_name} onChange={(event) => set('display_name', event.target.value)} /></label><label><span>Support email</span><input type="email" value={form.support_email} onChange={(event) => set('support_email', event.target.value)} /></label><label className="field-wide"><span>Admin notice</span><textarea rows={4} value={form.admin_notice} onChange={(event) => set('admin_notice', event.target.value)} /></label></div></div><div className="form-section"><div><h3>Operational alerts</h3><p>Control non-safety notification preferences.</p></div><div className="toggle-list"><label><span><strong>Daily operations digest</strong><small>Queue summary sent to assigned staff.</small></span><input type="checkbox" checked={form.digest_enabled} onChange={() => set('digest_enabled', !form.digest_enabled)} /><i /></label><label><span><strong>Moderation alerts</strong><small>Immediate notice for high-risk reports.</small></span><input type="checkbox" checked={form.moderation_alerts} onChange={() => set('moderation_alerts', !form.moderation_alerts)} /><i /></label></div></div></article><aside className="panel policy-card"><span className="policy-icon"><ShieldCheck size={19} /></span><span className="eyebrow">Policy boundary</span><h3>Scope cannot be changed here</h3><p>Campus assignments are resolved by the protected server from trusted staff records.</p><button className="text-button" onClick={() => onAction('Access policy is enforced by admin assignments.')}>Review access policy</button></aside></div></section>;
}
