import { useState } from 'react';
import { View } from 'react-native';
import { router } from 'expo-router';
import { goBackOrReplace } from '@/lib/navigation';
import { Body, Button, Chip, Field, IconButton, Screen, TopBar } from '@/components/ui';
import { apiQueryKey, useApiMutation } from '@/lib/api-hooks';
import { queryClient } from '@/lib/query';
import type { TeamRequest } from '@/lib/discovery';
import { useAppStore } from '@/store/useAppStore';

export default function NewTeam() {
  const toast = useAppStore((s) => s.showToast); const [name, setName] = useState(''); const [goal, setGoal] = useState(''); const [skills, setSkills] = useState(''); const [preferredSkills, setPreferredSkills] = useState(''); const [interests, setInterests] = useState(''); const [capacity, setCapacity] = useState('4'); const [commitment, setCommitment] = useState<'low' | 'moderate' | 'high' | 'flexible'>('flexible'); const [availability, setAvailability] = useState(''); const [deadline, setDeadline] = useState(''); const [completionDate, setCompletionDate] = useState(''); const [prompt, setPrompt] = useState('Why are you a good fit for this team?');
  const create = useApiMutation<TeamRequest, Record<string, unknown>>('/team-requests', 'POST', { onSuccess: async (team) => { await queryClient.invalidateQueries({ queryKey: ['api', 'team-requests'] }); toast({ type: 'success', message: 'Team request created.' }); router.replace(`/discover/tribe/team/${team.id}`); }, onError: (error) => toast({ type: 'error', message: error.message }) });
  const list = (value: string) => value.split(',').map((item) => item.trim()).filter(Boolean);
  const toIso = (value: string) => value.trim() ? new Date(`${value.trim()}T23:59:59`).toISOString() : null;
  return <Screen><TopBar title="Create a team request" subtitle="People apply; owner reviews" left={<IconButton icon="close" label="Close" onPress={() => goBackOrReplace('/discover/tribe')} />} /><Body style={{ marginTop: 12 }}>Describe a concrete campus goal, schedule, and needed skills. Team Finder stays independent from events and organizer roles.</Body><View style={{ gap: 16, marginTop: 20 }}><Field label="Team request title" value={name} onChangeText={setName} placeholder="e.g. Accessible Maps Lab" /><Field label="Project goal" value={goal} onChangeText={setGoal} multiline placeholder="What will this team build or accomplish?" /><Field label="Required skills (comma separated)" value={skills} onChangeText={setSkills} placeholder="Research, React Native, Maps" /><Field label="Preferred skills (optional)" value={preferredSkills} onChangeText={setPreferredSkills} placeholder="Design, Testing" /><Field label="Interests (optional)" value={interests} onChangeText={setInterests} placeholder="Accessibility, Civic Tech" /><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}><Chip label="Flexible" selected={commitment === 'flexible'} onPress={() => setCommitment('flexible')} /><Chip label="Low" selected={commitment === 'low'} onPress={() => setCommitment('low')} /><Chip label="Moderate" selected={commitment === 'moderate'} onPress={() => setCommitment('moderate')} /><Chip label="High" selected={commitment === 'high'} onPress={() => setCommitment('high')} /></View><Field label="Availability / schedule" value={availability} onChangeText={setAvailability} placeholder="Weeknights after 6 PM" /><Field label="Application deadline (YYYY-MM-DD)" value={deadline} onChangeText={setDeadline} placeholder="2026-08-20" /><Field label="Target completion (YYYY-MM-DD)" value={completionDate} onChangeText={setCompletionDate} placeholder="2026-10-01" /><Field label="Capacity" value={capacity} onChangeText={(value) => setCapacity(value.replace(/\D/g, ''))} keyboardType="numeric" /><Field label="Application prompt" value={prompt} onChangeText={setPrompt} multiline /><Button label="Create team request" loading={create.isPending} onPress={() => { try { create.mutate({ title: name.trim(), description: goal.trim(), neededTags: list(skills), preferredSkills: list(preferredSkills), interests: list(interests), capacity: Number(capacity) || undefined, commitmentLevel: commitment, availability: availability.trim() ? { summary: availability.trim() } : {}, applicationDeadline: toIso(deadline), targetCompletionDate: toIso(completionDate), applicationPrompt: prompt.trim() || undefined }); } catch { toast({ type: 'error', message: 'Use valid dates in YYYY-MM-DD format.' }); } }} disabled={!name.trim() || !goal.trim()} /></View></Screen>;
}
