import { useMemo, useState } from 'react';
import { Text, View } from 'react-native';
import { router } from 'expo-router';
import { goBackOrReplace } from '@/lib/navigation';
import { Ionicons } from '@expo/vector-icons';
import { Avatar, Badge, Body, Button, Card, Chip, Field, IconButton, Screen, SectionHeader, Segmented, StateView, TopBar } from '@/components/ui';
import { usePalette } from '@/theme/usePalette';
import { apiPatch, apiPost } from '@/lib/api';
import { apiQueryKey, useApiQuery } from '@/lib/api-hooks';
import { queryClient } from '@/lib/query';
import type { ApiEvent, ApiEventTeam } from '@/lib/events';
import { useAppStore } from '@/store/useAppStore';

type Tab = 'Overview' | 'Applications' | 'Roles' | 'Invitations';
type Connection = { id: string; otherUserId: string; state: string; isCrossCampus: boolean };

export default function OrganizerTeam() {
  const p = usePalette();
  const toast = useToast();
  const [tab, setTab] = useState<Tab>('Overview');
  const [editing, setEditing] = useState(false);
  const [purpose, setPurpose] = useState('');
  const [recruiting, setRecruiting] = useState(true);
  const teamsQuery = useApiQuery<ApiEventTeam[]>(apiQueryKey('organizer-event-teams'), '/events/event-teams/mine', {});
  const team = teamsQuery.data?.[0];
  const eventQuery = useApiQuery<ApiEvent>(apiQueryKey('event', team?.eventId), `/events/${team?.eventId}`, {}, { enabled: Boolean(team?.eventId) });
  const connectionsQuery = useApiQuery<Connection[]>(apiQueryKey('connections'), '/connections', {});
  const connections = (connectionsQuery.data ?? []).filter((connection) => connection.state === 'accepted' && !connection.isCrossCampus);
  const pending = useMemo(() => team?.applications.filter((application) => application.state === 'pending' || application.state === 'shortlisted') ?? [], [team]);

  if (teamsQuery.isLoading) return <Screen><StateView icon="hourglass-outline" title="Loading event team" detail="Fetching organizer workspace…" /></Screen>;
  if (teamsQuery.isError) return <Screen><StateView icon="cloud-offline" tone="danger" title="Team workspace unavailable" detail={teamsQuery.error.message} action="Retry" onAction={() => teamsQuery.refetch()} /></Screen>;
  if (!team || !eventQuery.data) return <Screen><StateView icon="people-outline" title="No organizer team" detail="Create an official event with a core team first." action="Create event" onAction={() => router.push('/organizer/create-event')} /></Screen>;

  const save = async () => { try { await apiPatch(`/events/${team.eventId}/teams/${team.id}`, { purpose: purpose.trim(), recruiting }); await teamsQuery.refetch(); setEditing(false); toast('Team workspace updated.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } };
  const review = async (applicationId: string, state: 'shortlisted' | 'accepted' | 'declined') => { try { await apiPatch(`/events/${team.eventId}/teams/${team.id}/applications/${applicationId}`, { state }); await queryClient.invalidateQueries({ queryKey: apiQueryKey('organizer-event-teams') }); toast(state === 'accepted' ? 'Member added with event title.' : `Application ${state}.`, 'success'); } catch (error) { toast((error as Error).message, 'error'); } };
  const invite = async (roleId: string, inviteeId: string) => { try { await apiPost(`/events/${team.eventId}/teams/${team.id}/invitations`, { roleId, inviteeId }); await teamsQuery.refetch(); toast('Invitation sent.', 'success'); } catch (error) { toast((error as Error).message, 'error'); } };

  return <Screen><TopBar title="Event team" subtitle={eventQuery.data.title} left={<IconButton icon="chevron-back" label="Back" onPress={() => goBackOrReplace('/organizer')} />} /><View style={{ borderRadius: 24, padding: 20, backgroundColor: team.accent ?? '#EAFBF4' }}><Badge label={team.recruiting ? 'Recruiting now' : 'Recruitment paused'} tone={team.recruiting ? 'success' : 'neutral'} icon={team.recruiting ? 'radio-button-on' : 'pause'} /><Text style={{ color: '#101828', fontSize: 27, lineHeight: 32, fontWeight: '900', marginTop: 14 }}>{team.name}</Text><Text style={{ color: '#475467', lineHeight: 20, marginTop: 7 }}>{team.purpose}</Text><View style={{ flexDirection: 'row', gap: 18, marginTop: 18 }}><View><Text style={{ color: '#101828', fontSize: 20, fontWeight: '900' }}>{team.members.length}</Text><Text style={{ color: '#475467', fontSize: 12 }}>on team</Text></View><View><Text style={{ color: '#101828', fontSize: 20, fontWeight: '900' }}>{pending.length}</Text><Text style={{ color: '#475467', fontSize: 12 }}>to review</Text></View></View></View><View style={{ marginTop: 16 }}><Segmented values={['Overview', 'Applications', 'Roles', 'Invitations'] as const} value={tab} onChange={setTab} /></View>{tab === 'Overview' ? <Overview team={team} editing={editing} purpose={purpose || team.purpose} setPurpose={setPurpose} recruiting={recruiting} setRecruiting={setRecruiting} onEdit={() => { setPurpose(team.purpose); setRecruiting(team.recruiting); setEditing(!editing); }} onSave={save} /> : null}{tab === 'Applications' ? <Applications team={team} onReview={review} /> : null}{tab === 'Roles' ? <Roles team={team} /> : null}{tab === 'Invitations' ? <Invitations team={team} connections={connections} onInvite={invite} /> : null}</Screen>;
}

function Overview({ team, editing, purpose, setPurpose, recruiting, setRecruiting, onEdit, onSave }: { team: ApiEventTeam; editing: boolean; purpose: string; setPurpose: (value: string) => void; recruiting: boolean; setRecruiting: (value: boolean) => void; onEdit: () => void; onSave: () => Promise<void> }) { const p = usePalette(); return <><SectionHeader title="Team charter" action={editing ? 'Cancel' : 'Edit'} onAction={onEdit} />{editing ? <Card style={{ gap: 14 }}><Field label="What this team owns" value={purpose} onChangeText={setPurpose} multiline /><View style={{ flexDirection: 'row', gap: 9 }}><Button compact variant={recruiting ? 'primary' : 'secondary'} label={recruiting ? 'Recruitment on' : 'Recruitment off'} icon={recruiting ? 'radio-button-on' : 'pause'} onPress={() => setRecruiting(!recruiting)} /><View style={{ flex: 1 }}><Button compact label="Save changes" onPress={onSave} /></View></View></Card> : <Card><Body>{team.purpose}</Body><View style={{ marginTop: 14, backgroundColor: p.brandSoft, borderRadius: 12, padding: 12, flexDirection: 'row', gap: 8 }}><Ionicons name="information-circle" size={18} color={p.brand} /><Text style={{ flex: 1, color: p.text, fontSize: 12, lineHeight: 18 }}>Organizer keeps event safety and capacity control. Team members receive scoped event titles.</Text></View></Card>}<SectionHeader title="People with event titles" />{team.members.filter((member) => member.state === 'active').map((member) => <Card key={member.id} style={{ marginBottom: 10, padding: 13 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 11 }}><Avatar initials={member.displayName.slice(0, 2).toUpperCase()} accent="#E9E6FF" /><View style={{ flex: 1 }}><Text style={{ color: p.ink, fontWeight: '800' }}>{member.displayName}</Text><Text style={{ color: p.brand, fontSize: 12, fontWeight: '800', marginTop: 3 }}>{member.title}</Text></View><Badge label="Team member" tone="brand" /></View></Card>)}</> }

function Applications({ team, onReview }: { team: ApiEventTeam; onReview: (id: string, state: 'shortlisted' | 'accepted' | 'declined') => Promise<void> }) { const p = usePalette(); return <><SectionHeader title={`${team.applications.length} applications`} />{team.applications.map((application) => { const role = team.roles.find((item) => item.id === application.roleId); const full = role ? role.filled >= role.openings && application.state !== 'accepted' : true; return <Card key={application.id} style={{ marginBottom: 12 }}><View style={{ flexDirection: 'row', gap: 11, alignItems: 'center' }}><Avatar initials={application.applicantName.slice(0, 2).toUpperCase()} accent="#EAFBF4" /><View style={{ flex: 1 }}><Text style={{ color: p.ink, fontWeight: '800' }}>{application.applicantName}</Text><Text style={{ color: p.brand, fontSize: 12, fontWeight: '800', marginTop: 3 }}>{role?.title ?? 'Role'}</Text></View><Badge label={application.state} tone={application.state === 'accepted' ? 'success' : application.state === 'declined' ? 'danger' : 'warning'} /></View><Body style={{ marginTop: 12 }}>{application.note || 'No note provided.'}</Body>{full ? <Body muted style={{ marginTop: 10 }}>Role full. Increase openings before accepting.</Body> : null}{application.state === 'pending' ? <View style={{ flexDirection: 'row', gap: 9, marginTop: 14 }}><View style={{ flex: 1 }}><Button compact variant="secondary" label="Shortlist" onPress={() => onReview(application.id, 'shortlisted')} /></View><View style={{ flex: 1 }}><Button compact disabled={full} label="Add to team" onPress={() => onReview(application.id, 'accepted')} /></View></View> : application.state === 'shortlisted' ? <View style={{ flexDirection: 'row', gap: 9, marginTop: 14 }}><View style={{ flex: 1 }}><Button compact variant="ghost" label="Decline" onPress={() => onReview(application.id, 'declined')} /></View><View style={{ flex: 1 }}><Button compact disabled={full} label="Add to team" onPress={() => onReview(application.id, 'accepted')} /></View></View> : null}</Card> })}{!team.applications.length ? <Body muted>No applications yet.</Body> : null}</> }

function Roles({ team }: { team: ApiEventTeam }) { const p = usePalette(); return <><SectionHeader title="Open roles" />{team.roles.map((role) => <Card key={role.id} style={{ marginBottom: 11 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ flex: 1 }}><Text style={{ color: p.ink, fontSize: 16, fontWeight: '800' }}>{role.title}</Text><Body muted style={{ marginTop: 4 }}>{role.description}</Body></View><Badge label={`${role.filled}/${role.openings}`} tone={role.filled >= role.openings ? 'success' : 'warning'} /></View><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 }}>{role.skills.map((skill) => <Chip key={skill} label={skill} />)}</View></Card>)}</> }

function Invitations({ team, connections, onInvite }: { team: ApiEventTeam; connections: Connection[]; onInvite: (roleId: string, inviteeId: string) => Promise<void> }) { const p = usePalette(); return <><SectionHeader title="Accepted connections" />{team.roles.map((role) => <Card key={role.id} style={{ marginBottom: 12 }}><Text style={{ color: p.ink, fontWeight: '900' }}>{role.title}</Text><Body muted style={{ marginTop: 4 }}>Invite connected same-campus members.</Body>{connections.length ? connections.map((connection) => <Button key={`${role.id}-${connection.otherUserId}`} compact variant="secondary" label={`Invite ${connection.otherUserId.slice(0, 8)}`} icon="person-add" onPress={() => onInvite(role.id, connection.otherUserId)} />) : <Body muted style={{ marginTop: 10 }}>No accepted same-campus connections available.</Body>}</Card>)}</> }

function useToast() { const show = useAppStore((s) => s.showToast); return (message: string, type: 'success' | 'error' | 'info') => show({ type, message }); }
